export ZSH="/usr/share/oh-my-zsh"
ZSH_THEME="miloshadzic"
DISABLE_AUTO_UPDATE="true"
DISABLE_LS_COLORS="true"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="yyyy-mm-dd"
plugins=(archlinux command-not-found git golang npm sudo yarn)
source $ZSH/oh-my-zsh.sh

# User configuration
export MODE=DEV
export GOPATH="/home/`whoami`/go"
export GO111MODULE=on
export GOPROXY=https://goproxy.cn
export PATH="$PATH:/home/`whoami`/go/bin:/home/`whoami`/.local/bin:/usr/local/bin"
export ANDROID_HOME=/opt/android-sdk
export JAVA_HOME=/usr/lib/jvm/java-14-openjdk
export PATH={$PATH}:{$ANDROID_HOME}/tools
export PATH={$PATH}:{$ANDROID_HOME}/platform-tools
export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
[ -d ~/.pub-cache/bin ] && export PATH="$PATH":"$HOME/.pub-cache/bin"
[ -d ~/.yarn/bin ] && export PATH="$PATH":"$HOME/.yarn/bin"
[[ -f ~/.custom_source ]] && source ~/.custom_source

##################################
# alisa
##################################
alias vi="nvim"
alias cnpm="npm --registry=https://registry.npm.taobao.org \
--cache=$HOME/.npm/.cache/cnpm \
--disturl=https://npm.taobao.org/dist \
--userconfig=$HOME/.cnpmrc"
alias pp="pip install --user "
alias jj="sudo pacman -S "

# tabtab source for electron-forge package
# uninstall by removing these lines or running `tabtab uninstall electron-forge`
[[ -f /home/jone/.config/yarn/global/node_modules/tabtab/.completions/electron-forge.zsh ]] && . /home/jone/.config/yarn/global/node_modules/tabtab/.completions/electron-forge.zsh
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"
