export ZSH="/home/jone/.oh-my-zsh"
ZSH_THEME="miloshadzic"
DISABLE_AUTO_UPDATE="true"
DISABLE_LS_COLORS="true"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="yyyy-mm-dd"
plugins=(archlinux command-not-found git go npm sudo yarn)
source $ZSH/oh-my-zsh.sh

# User configuration
export MODE=DEV
export GOPATH="/home/jone/go"
export GO111MODULE=on
export GOPROXY=https://goproxy.cn
export PATH="$PATH:/home/`whoami`/go/bin:/home/`whoami`/.local/bin:/usr/local/bin:/opt/flutter/bin"
export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
export ANDROID_HOME=/opt/android-sdk
export PATH={$PATH}:{$ANDROID_HOME}/tools
export PATH={$PATH}:{$ANDROID_HOME}/platform-tools
[ -d ~/.pub-cache/bin ] && export PATH="$PATH":"$HOME/.pub-cache/bin"
[[ -f /home/jone/.custom_source ]] && source /home/jone/.custom_source
export FZF_DEFAULT_COMMAND="fd --exclude={.git,.vscode,node_modules,venv} --type f"

##################################
# alisa
##################################
alias vi="nvim"
alias cnpm="npm --registry=https://registry.npm.taobao.org \
--cache=$HOME/.npm/.cache/cnpm \
--disturl=https://npm.taobao.org/dist \
--userconfig=$HOME/.cnpmrc"
alias pp="pip install --user "

# tabtab source for electron-forge package
# uninstall by removing these lines or running `tabtab uninstall electron-forge`
[[ -f /home/jone/.config/yarn/global/node_modules/tabtab/.completions/electron-forge.zsh ]] && . /home/jone/.config/yarn/global/node_modules/tabtab/.completions/electron-forge.zsh


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
