export MODE=DEV
export PATH="$PATH:/home/`whoami`/go/bin:/opt/flutter/bin"
export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
export ANDROID_HOME=/opt/android-sdk
export PATH={$PATH}:{$ANDROID_HOME}/tools
export PATH={$PATH}:{$ANDROID_HOME}/platform-tools

alias vi="nvim"

source ~/.config/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle command-not-found

# Syntax highlighting bundle.
#antigen bundle zsh-users/zsh-syntax-highlighting

# Load the theme.
antigen theme wezm

# Tell Antigen that you're done.
antigen apply

