export ZSH="/home/`whoami`/.oh-my-zsh"
export MODE=DEV
export PATH="$PATH:/home/`whoami`/go/bin"

ZSH_THEME="robbyrussell"

DISABLE_AUTO_UPDATE="true"
DISABLE_LS_COLORS="true"
ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"

plugins=(
  git archlinux cp docker docker-compose git
  go golang npm pip python sudo yarn
)

source $ZSH/oh-my-zsh.sh


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
