#!/bin/sh

jbase (){
    echo 'export GTK_IM_MODULE=fcitx' > ~/.xinitrc
    echo 'export QT_IM_MODULE=fcitx' >> ~/.xinitrc
    echo 'export XMODIFIERS=fcitx' >> ~/.xinitrc
}

ji3 () {
    echo 'exec i3' >> ~/.xinitrc
}

jgnome () {
    echo "export GDK_BACKEND=x11" >> ~/.xinitrc
    echo "exec gnome-session" >> ~/.xinitrc
}

jdeepin () {
    echo "exec startdde" >> ~/.xinitrc
}

jlxde () {
    echo "exec startlxde" >> ~/.xinitrc
}

jkde() {
    echo "exec startkde" >> ~/.xinitrc
}



jmain() {
    jbase

    case $1 in
        "i"|"i3")          ji3;;
        "l"|"lxde")        jlxde;;
        "d"|"deepin")      jdeepin;;
        "g"|"gnome")       jgnome;;
        "k"|"kde")         jkde;;
        *)                 ji3;;
    esac

    startx
}


jmain $@
