#!/bin/bash

# 更新hosts文件：
#		屏蔽广告网站
#		访问国内被屏蔽网站

host="/etc/hosts"

urls=(\
	"https://hosts.nfz.moe/127.0.0.1/full/hosts" \
	"https://raw.githubusercontent.com/googlehosts/hosts/master/hosts-files/hosts" \
	)


echo "127.0.0.1		localhost" > $host

for url in ${urls[@]}; do
	echo "" >> $host
	curl $url >> $host;
done
